### Линейная алгебра. Домашнее задание.

#### Урок 3.

##### 1. Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;


$AB$ не определено

$BA : 2 \times 2$

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;


$AB: 2 \times 3$

$BA$ не определено

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;


$AB: 8 \times 8$

$BA: 3 \times 3$

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.



$AB: 4 \times 4$

$BA: 4 \times 4$

##### 2. Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A + B = \begin{pmatrix} 1+4 & -2-1\\ 3+0 & 0+5\end{pmatrix} = \begin{pmatrix} 5 & -3\\ 3 & 5\end{pmatrix} $


$AB = \begin{pmatrix} 1*4 + (-2)*0 & 1*(-1)+ (-2)*5\\ 3*4 + 0*0 & 3*(-1)+ 0*5 \end{pmatrix} = \begin{pmatrix} 4 & -11\\ 12 & -3\end{pmatrix} $

$BA = \begin{pmatrix} 4*1 + (-1)*3 & 4*(-2)+ (-1)*0\\ 0*1 + 5*3 & 0*(-2)+ 5*0 \end{pmatrix} = \begin{pmatrix} 1 & -8\\ 15 & 0\end{pmatrix} $

In [82]:
import numpy as np

In [83]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f"A + B\n {(A + B)}\n")
print(f"AB\n {np.dot(A, B)}")
print(f"BA\n {np.dot(B, A)}")

A + B
 [[ 5 -3]
 [ 3  5]]

AB
 [[  4 -11]
 [ 12  -3]]
BA
 [[ 1 -8]
 [15  0]]


##### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C = 3 \begin{pmatrix} 1 & 7 \\ 3 & -6 \end{pmatrix} - 2\begin{pmatrix}0 & 5 \\ 2 & -1 \end{pmatrix} + 4\begin{pmatrix} 2 & -4 \\ 1 & 1 \end{pmatrix} =  \begin{pmatrix} 3 & 21 \\ 9 & -18 \end{pmatrix} + \begin{pmatrix} 0 & -10 \\ -4 & 2 \end{pmatrix} + \begin{pmatrix} 8 & -16 \\ 4 & 4 \end{pmatrix} = \begin{pmatrix} 11 & -5 \\ 9 & -12 \end{pmatrix}$

In [84]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f"3A - 2B + 4C =\n {(3*A - 2*B + 4*C)}\n")


3A - 2B + 4C =
 [[ 11  -5]
 [  9 -12]]



##### 4. Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$,
$A^{T}=\begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3 
\end{pmatrix}$

$AA^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}\begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3 
\end{pmatrix} = \begin{pmatrix}
4*4 + 1*1 & 4*5 + 1*(-2) & 4*2 + 1*3 \\ 
5*4 +(-2)*1 & 5*5 +(-2)*(-2) & 5*2 + (-2)*3 \\ 
2*4 + 3*1 & 2*5 + 3*(-2) & 2*2 + 3*3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11 \\ 
18 & 29 & 4 \\ 
11 & 4 & 13
\end{pmatrix}
$

$A^{T}A = \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3 
\end{pmatrix}\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
4*4 + 5*5 + 2*2 & 4*1 + 5*(-2) + 2*3\\ 
1*4 + (-2)*5 +3*2 & 1*1 + (-2)*(-2) + 3*3\\ 
\end{pmatrix} = \begin{pmatrix}
45 & 0 \\ 
0 & 14
\end{pmatrix}
$

In [85]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f"A = \n{A}")
print(f"AT = \n{A.T}")

A = 
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
AT = 
[[ 4  5  2]
 [ 1 -2  3]]


In [86]:
print(f"A*AT = \n{np.dot(A, A.T)}")
print(f"AT*A = \n{np.dot(A.T, A)}")

A*AT = 
[[17 18 11]
 [18 29  4]
 [11  4 13]]
AT*A = 
[[45  0]
 [ 0 14]]


##### 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [87]:
def mul_matrix(a, b):    
    def matrix_dim(matrix):
        rows = len(matrix)
        cols = set(map(len, matrix))
        if len(cols) > 1:
            print (f"Ошибка размерности матрицы:\n {matrix}\nКоличество столбцов в каждой строке внутри матрицы должно быть одинаковым!")
            return False
        return rows, cols.pop()
   
    a_dim, b_dim = map(matrix_dim, (a, b))
   
    if a_dim and b_dim:
        if a_dim[1] != b_dim[0]:
            print(f"Ошибка. Размерность данных матриц делает их произведение неопределённым.")
            return False
        
        ab=[]
        for row in a:
            ab_row=[]
            for i in range(b_dim[0]):
                buf = 0
                for j in range(b_dim[1]):
                    buf += row[j]*b[j][i]
                ab_row.append(buf)
            ab.append(ab_row)
        return ab
    else:
        return False            

In [88]:
A = [[1, 2], [2, 3], [6, 3]]
B = [[0, 5], [2, -1]]

In [89]:
mul_matrix(A, B)

[[4, 3], [6, 7], [6, 27]]

In [90]:
A = np.array([[1, 2], [2, 3], [6, 3]])
B = np.array([[0, 5], [2, -1]])
np.dot(A, B)

array([[ 4,  3],
       [ 6,  7],
       [ 6, 27]])