### Линейная алгебра. Домашнее задание.

#### Урок 3.

##### 1. Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;


$AB$ не определено

$BA : 2 \times 2$

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;


$AB: 2 \times 3$

$BA$ не определено

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;


$AB: 8 \times 8$

$BA: 3 \times 3$

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.



$AB: 4 \times 4$

$BA: 4 \times 4$

##### 2. Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A + B = \begin{pmatrix} 1+4 & -2-1\\ 3+0 & 0+5\end{pmatrix} = \begin{pmatrix} 5 & -3\\ 3 & 5\end{pmatrix} $


$AB = \begin{pmatrix} 1*4 + (-2)*0 & 1*(-1)+ (-2)*5\\ 3*4 + 0*0 & 3*(-1)+ 0*5 \end{pmatrix} = \begin{pmatrix} 4 & -11\\ 12 & -3\end{pmatrix} $

$BA = \begin{pmatrix} 4*1 + (-1)*3 & 4*(-2)+ (-1)*0\\ 0*1 + 5*3 & 0*(-2)+ 5*0 \end{pmatrix} = \begin{pmatrix} 1 & -8\\ 15 & 0\end{pmatrix} $

In [1]:
import numpy as np

In [14]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f"A + B\n {(A + B)}\n")
print(f"AB\n {np.dot(A, B)}")
print(f"BA\n {np.dot(B, A)}")

A + B
 [[ 5 -3]
 [ 3  5]]

AB
 [[  4 -11]
 [ 12  -3]]
BA
 [[ 1 -8]
 [15  0]]


##### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C = 3 \begin{pmatrix} 1 & 7 \\ 3 & -6 \end{pmatrix} - 2\begin{pmatrix}0 & 5 \\ 2 & -1 \end{pmatrix} + 4\begin{pmatrix} 2 & -4 \\ 1 & 1 \end{pmatrix} =  \begin{pmatrix} 3 & 21 \\ 9 & -18 \end{pmatrix} + \begin{pmatrix} 0 & -10 \\ -4 & 2 \end{pmatrix} + \begin{pmatrix} 8 & -16 \\ 4 & 4 \end{pmatrix} = \begin{pmatrix} 11 & -5 \\ 9 & -12 \end{pmatrix}$

In [15]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f"3A - 2B + 4C =\n {(3*A - 2*B + 4*C)}\n")


3A - 2B + 4C =
 [[ 11  -5]
 [  9 -12]]

